name: ai_pushup_counter
description: "AI Push-up Counter MVP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  camera: ^0.11.0+2
  google_mlkit_pose_detection: ^0.12.0
  flutter_tts: ^4.2.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  android: false
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
